# Generated by Django 5.2.1 on 2025-06-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_producto_options_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de alquiler semanal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_renta',
            field=models.CharField(choices=[('mes', 'Por mes'), ('semana', 'Por semana'), ('ambos', 'Mes o semana')], default='mes', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('m2', 'Metros cuadrados')], default='unidad', max_length=20),
        ),
    ]
