# Generated by Django 5.2.1 on 2025-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_pedido_direccion_obra_alter_pedido_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='duracion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='tipo_renta',
            field=models.CharField(default='mes', max_length=20),
        ),
    ]
