# Generated by Django 5.2.1 on 2025-06-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='clientes.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='clientes.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_recibe', models.CharField(max_length=100)),
                ('cedula_recibe', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('estado_productos', models.TextField(blank=True)),
                ('firma', models.CharField(blank=True, max_length=100)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo_obra', to='clientes.pedido')),
            ],
        ),
    ]
