# Generated by Django 5.2.1 on 2025-06-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_devolucion_devolucionproducto_reciboobra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AlterModelOptions(
            name='devolucionproducto',
            options={'verbose_name': 'Producto Devuelto', 'verbose_name_plural': 'Productos Devueltos'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoproducto',
            options={'verbose_name': 'Producto en Pedido', 'verbose_name_plural': 'Productos en Pedido'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='reciboobra',
            options={'verbose_name': 'Recibo de Obra', 'verbose_name_plural': 'Recibos de Obra'},
        ),
        migrations.AlterModelOptions(
            name='remision',
            options={'verbose_name': 'Remisión', 'verbose_name_plural': 'Remisiones'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='cedula_recibe',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='estado_productos',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='nombre_recibe',
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.pedido'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='tipo_renta',
            field=models.CharField(choices=[('mes', 'Mes'), ('semana', 'Semana')], default='mes', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_renta',
            field=models.CharField(choices=[('mes', 'Mes'), ('semana', 'Semana')], default='mes', max_length=20),
        ),
        migrations.AlterField(
            model_name='reciboobra',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.pedido'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.pedido'),
        ),
    ]
