# Generated by Django 5.2.1 on 2025-06-11 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_options_alter_devolucion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboobra',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(editable=False, max_length=13, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ReciboObraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('con_danios', 'Con daños'), ('danado', 'Dañado completamente')], default='completo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.producto')),
                ('recibo_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='clientes.reciboobra')),
            ],
            options={
                'verbose_name': 'Producto en Recibo de Obra',
                'verbose_name_plural': 'Productos en Recibo de Obra',
            },
        ),
    ]
